PROMPT=' $FX[bold]$FG[032]%c$(git_prompt_info) $FX[reset]'

ZSH_THEME_GIT_PROMPT_PREFIX=" $FG[015]($FG[001]"
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY="$FG[015]) $FG[154]✗"
ZSH_THEME_GIT_PROMPT_CLEAN="$FG[015])"
